### ISSUE TITLE
Image DEST having issues

### ISSUE THREAD

**Issue by mikeumus** [PixmSecurity/PhishTank-Node-Screenshot-Scrape#1]
and some memory issues. @IonicaBizau if you're around for another session sometime to check this out with me. Thanks.

It's going this:

```
!! Url (Myweb.tiscali.co.uk/speel/paint/storey.htm) FAILED:  { [Error: ENOENT: no such file or directory, open 'images/screenshots/Myweb.tiscali.co.uk/speel/paint/storey.htm - 1444796435821.png.ce02976eef1edd061581df853a33f401']
```

**Comment by IonicaBizau** [comment]
@mikeumus We have a timezone difference, but if you like, now we can do it (just create a preferred expert session). Thanks! :cake:

**Comment by mikeumus** [comment]
Roger that, is now good?

**Comment by IonicaBizau** [comment]
@mikeumus Yes! I just woke up! :smile:

**Comment by mikeumus** [comment]
Do you have a username that I "prefer" or how does that work?

**Comment by IonicaBizau** [comment]
@mikeumus Actually, just create the session and I will be the first to enter there. If you create a preferred session we will have to wait 30 minutes.

**Comment by mikeumus** [comment]
okay roger that.

**Comment by mikeumus** [comment]
@IonicaBizau got it with some regex! Thanks again. :smiley:

**Comment by IonicaBizau** [comment]
@mikeumus Always welcome! :smile: It was a nice start of the day. :sunny:

**Comment by mikeumus** [comment]
Hey @IonicaBizau, it's also not liking websites ending with forward slashes like this one:
- `Bajaquest.com/cavepaintings/`

I don't know if the regex is handling it correctly, getting some errors about the DEST_DIR again like above.

**Comment by IonicaBizau** [comment]
@mikeumus Oh, just do this: replace `/\//` with `/\//g` (add the global flag). That should be the problem, lol. :laughing:

**Comment by IonicaBizau** [comment]
@mikeumus Did it work?

**Comment by mikeumus** [comment]
@IonicaBizau, haven't tested it since as I got all the screenshots I needed but I'll let you know if I run the script again and save that trick up my sleeve for later as well. Thanks Ionica.

**Comment by IonicaBizau** [comment]
@mikeumus You're welcome! :joy: When you need help, just ping me!
